Adds new set of AWS codebundles
runwhen-contrib/rw-cli-codecollection pull request #355
Opened 2024-04-24 20:08 UTC by jon-funk

- EKS fargate health scan
- Elasticache redis scan
- S3 report
- Lambda Health scan

2024-04-25 01:02 UTC, stewartshea requested changes
Some minor notes, mostly to share some knowledge. I see other example where runbook has a list of locations, so maybe both ways work, but in general the runbook should be a singular value

2024-04-25 01:02 UTC, stewartshea commented on codebundles/aws-eks-fargate-cluster-health/.runwhen/templates/aws-eks-fargate-cluster-health-taskset.yaml
> +  locations:
location: {{default_location}}

2024-04-25 01:02 UTC, stewartshea commented on codebundles/aws-eks-fargate-cluster-health/.runwhen/generation-rules/aws-eks-fargate-cluster-health.yaml
> +        - baseName: aws-eks-fargate-cluster-health
this basename is a little long. The basename is used as the "human readable component" of the slx name, but gets shortened if it's too long. could try something like eks-fargate-health to shave off some characters

2024-04-25 01:02 UTC, stewartshea commented on codebundles/aws-eks-fargate-cluster-health/.runwhen/generation-rules/aws-eks-fargate-cluster-health.yaml
> +              templateName: aws-eks-fargate-cluster-health-sli.yaml
by default workspace builder will look for baseTemplateName-type.yaml, so you don't really need to set the templatename here unless the template itself is of a different name such as the runbook/taskset naming difference.

2024-04-25 01:02 UTC, stewartshea commented on codebundles/aws-elasticache-redis-health/.runwhen/templates/aws-elasticache-redis-health-taskset.yaml
> +  locations:
location: {{default_location}}

2024-04-25 01:02 UTC, stewartshea commented on codebundles/aws-lambda-health/.runwhen/generation-rules/aws-lambda-health.yaml
> +              templateName: aws-lambda-health-sli.yaml
don't need the templateName here

2024-04-25 01:02 UTC, stewartshea commented on codebundles/aws-lambda-health/.runwhen/templates/aws-lambda-health-taskset.yaml
> +  locations:
location: {{default_location}}

2024-04-25 01:02 UTC, stewartshea commented on codebundles/aws-s3-bucket-storage-report/.runwhen/templates/aws-s3-bucket-storage-report-taskset.yaml
> +  locations:
location: {{default_location}}

2024-05-16 16:27 UTC, jon-funk commented on codebundles/aws-eks-health/runbook.robot
> +        ...    next_steps=Check the AWS Management Console for the health status of the EKS Fargate cluster.
Update to "fetch X logs from cloudtrail"

2024-05-16 16:29 UTC, jon-funk commented on codebundles/aws-eks-health/.runwhen/generation-rules/aws-eks-health.yaml
> +    - resourceTypes:
Send note for updating to "match on type and not instance"

2024-05-16 16:36 UTC, jon-funk commented on codebundles/aws-elasticache-redis-health/runbook.robot
> +
add task for fetch cloudtrail logs

2024-05-16 16:37 UTC, jon-funk commented on codebundles/aws-elasticache-redis-health/runbook.robot
> +#     RW.Core.Add Pre To Report    ${process.stdout}
cleanup

2024-05-16 16:38 UTC, jon-funk commented on codebundles/aws-lambda-health/runbook.robot
> +        ...    reproduce_hint=Check the AWS Management Console for the status of the Lambda function.
update nextsteps (try generate link)

2024-05-22 18:32 UTC, merged